// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEkr_ounsZmQ_hCP0UR53KV4rAl_5nvI',
    appId: '1:835949221258:web:2d8c9ff3aba5eb39dae473',
    messagingSenderId: '835949221258',
    projectId: 'pokedex-app-e3c2a',
    authDomain: 'pokedex-app-e3c2a.firebaseapp.com',
    storageBucket: 'pokedex-app-e3c2a.firebasestorage.app',
    measurementId: 'G-635VHQ4BRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6uirC3CgfBmDW26ozpMXCh9kpUrnC8c',
    appId: '1:835949221258:android:840416873628eae6dae473',
    messagingSenderId: '835949221258',
    projectId: 'pokedex-app-e3c2a',
    storageBucket: 'pokedex-app-e3c2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4xh97HcpF95FjZgUBwtG-82c3swEdho',
    appId: '1:835949221258:ios:a726bee6094d94b8dae473',
    messagingSenderId: '835949221258',
    projectId: 'pokedex-app-e3c2a',
    storageBucket: 'pokedex-app-e3c2a.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4xh97HcpF95FjZgUBwtG-82c3swEdho',
    appId: '1:835949221258:ios:a726bee6094d94b8dae473',
    messagingSenderId: '835949221258',
    projectId: 'pokedex-app-e3c2a',
    storageBucket: 'pokedex-app-e3c2a.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEkr_ounsZmQ_hCP0UR53KV4rAl_5nvI',
    appId: '1:835949221258:web:0fafd61f1a25c1a0dae473',
    messagingSenderId: '835949221258',
    projectId: 'pokedex-app-e3c2a',
    authDomain: 'pokedex-app-e3c2a.firebaseapp.com',
    storageBucket: 'pokedex-app-e3c2a.firebasestorage.app',
    measurementId: 'G-LKBKQL6GXV',
  );
}
