// Mocks generated by Mockito 5.4.5 from annotations
// in pokedex_app/test/save_local_service/save_local_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:pokedex_app/core/services/local_storage/interfaces/serializable_model.dart'
    as _i4;
import 'package:pokedex_app/core/services/local_storage/services/save_into_storage.dart'
    as _i5;
import 'package:pokedex_app/models/user/user_infos.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterSecureStorage_0 extends _i1.SmartFake
    implements _i2.FlutterSecureStorage {
  _FakeFlutterSecureStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserInfos].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInfos extends _i1.Mock implements _i3.UserInfos {
  MockUserInfos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [SaveIntoStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveIntoStorage<T extends _i4.SerializableModel> extends _i1.Mock
    implements _i5.SaveIntoStorage<T> {
  MockSaveIntoStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterSecureStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFlutterSecureStorage_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.FlutterSecureStorage);

  @override
  set storage(_i2.FlutterSecureStorage? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> save(T? object) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [object],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getTokens() => (super.noSuchMethod(
        Invocation.method(
          #getTokens,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  String generateTokenByObject(Object? object) => (super.noSuchMethod(
        Invocation.method(
          #generateTokenByObject,
          [object],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateTokenByObject,
            [object],
          ),
        ),
      ) as String);

  @override
  _i6.Future<void> saveTokens(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateToken(
    String? oldToken,
    String? newToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [
            oldToken,
            newToken,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeAllTokens() => (super.noSuchMethod(
        Invocation.method(
          #removeAllTokens,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
